apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volga-on-demand-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: volga-on-demand.svoe.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: on-demand-service-external
                port:
                  number: 1122