apiVersion: apps/v1
kind: Deployment
metadata:
  name: volga-perf-test-deployment
spec:
  selector:
    matchLabels:
      name: volga-perf-test-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: volga-perf-test-deployment
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: volga-perf-test-container
        image: 050011372339.dkr.ecr.ap-northeast-1.amazonaws.com/volga/perf-test:v2
        resources:
          limits:
            memory: 16Gi
          requests:
            cpu: 7
            memory: 14Gi
      tolerations:
        - key: workload-type
          operator: Equal
          value: ray
          effect: NoSchedule
        - key: ray-role
          operator: Equal
          value: worker
          effect: NoSchedule