apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: locust-cluster
  region: ap-northeast-1
# https://www.davidc.net/sites/default/subnets/subnets.html for cidr split
vpc:
  id: vpc-02eba23ddbbf5c077
  cidr: 10.100.0.0/16
  subnets:
    public:
      ap-northeast-1a:
        id: subnet-0875b1951471ddede
      ap-northeast-1c:
        id: subnet-0e385e00f0b80e03f
iam:
  withOIDC: true
addons:
- name: amazon-cloudwatch-observability
  attachPolicy:
    Version: "2012-10-17"
    Statement:
      - Effect: Allow
        Action: '*' # TODO THIS IS BAD FOR PROD
        Resource: '*'

nodeGroups:
  - name: locust-workers
    instanceType: t2.medium
    desiredCapacity: 2
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    ssh:
      allow: true
    amiFamily: Ubuntu2204