apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: volga-test-cluster
  region: ap-northeast-1
# https://www.davidc.net/sites/default/subnets/subnets.html for cidr split
vpc:
  id: vpc-02eba23ddbbf5c077
  cidr: 10.100.0.0/16
  subnets:
    public:
      ap-northeast-1a:
        id: subnet-0875b1951471ddede
      ap-northeast-1c:
        id: subnet-0e385e00f0b80e03f
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - 'arn:aws:iam::050011372339:policy/AWSLoadBalancerControllerIAMPolicy'
addons:
- name: amazon-cloudwatch-observability
  attachPolicy:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Action: '*' # TODO THIS IS BAD FOR PROD
        Resource: '*'
- name: aws-ebs-csi-driver
  attachPolicy:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Action: '*'
        Resource: '*'

nodeGroups:
  - name: shared
    instanceType: t3.medium
    desiredCapacity: 4
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    ssh:
      allow: true
    amiFamily: Ubuntu2204
  - name: ray-head
    instanceType: t3.medium
    desiredCapacity: 1
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    ssh:
      allow: true
    amiFamily: Ubuntu2204
    labels:
      workload-type: ray
      ray-role: head
    taints:
      - key: workload-type
        value: ray
        effect: NoSchedule
      - key: ray-role
        value: head
        effect: NoSchedule
  - name: ray-workers
    instanceType: t3.medium
    desiredCapacity: 2
    ssh:
      allow: true
    amiFamily: Ubuntu2204
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    labels:
      workload-type: ray
      ray-role: worker
    taints:
      - key: workload-type
        value: ray
        effect: NoSchedule
      - key: ray-role
        value: worker
        effect: NoSchedule
  - name: scylla-workers
    instanceType: t3.medium
    desiredCapacity: 2
    ssh:
      allow: true
    amiFamily: Ubuntu2204
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    labels:
      workload-type: scylla
    taints:
      - key: workload-type
        value: scylla
        effect: NoSchedule
  - name: locust-workers
    instanceType: t3.medium
    desiredCapacity: 2
    ssh:
      allow: true
    amiFamily: Ubuntu2204
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    labels:
      workload-type: locust
    taints:
      - key: workload-type
        value: locust
        effect: NoSchedule