apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: volga-test-cluster
  region: ap-northeast-1
# https://www.davidc.net/sites/default/subnets/subnets.html for cidr split
vpc:
  id: vpc-02eba23ddbbf5c077
  cidr: 10.100.0.0/16
  subnets:
    public:
      ap-northeast-1a:
        id: subnet-0875b1951471ddede
      ap-northeast-1c:
        id: subnet-0e385e00f0b80e03f
nodeGroups:
  - name: shared
    instanceType: t3.medium
#    instanceType: c5.xlarge
    desiredCapacity: 1
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    ssh:
      allow: true
    amiFamily: Ubuntu2204
  - name: ray-head
#    instanceType: c5.xlarge
    instanceType: t3.medium
    desiredCapacity: 1
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    ssh:
      allow: true
    amiFamily: Ubuntu2204
    labels:
      workload-type: ray
      ray-role: head
    taints:
      - key: workload-type
        value: ray
        effect: NoSchedule
      - key: ray-role
        value: head
        effect: NoSchedule
  - name: ray-workers
#    instanceType: c5.2xlarge
    instanceType: t3.medium
    desiredCapacity: 0
    ssh:
      allow: true
    amiFamily: Ubuntu2204
#    minSize: 2
#    maxSize: 2
#    instancesDistribution:
#      maxPrice: 0.1
#      instanceTypes:
#        - c5.2xlarge
#      onDemandBaseCapacity: 0
#      onDemandPercentageAboveBaseCapacity: 0
    subnets:
      - ap-northeast-1a
    kubeletExtraConfig:
      cpuCFSQuota: false
    labels:
      workload-type: ray
      ray-role: worker
    taints:
      - key: workload-type
        value: ray
        effect: NoSchedule
      - key: ray-role
        value: worker
        effect: NoSchedule