environments:
  default:
    values:
      - env_values.yaml
releases:
  - chart: kuberay/kuberay-operator
    name: kuberay-operator
    namespace: ray-system
    values:
      - values/kuberay/kuberay-operator/values.yaml.gotmpl
  - chart: kuberay/ray-cluster
    name: ray-cluster
    namespace: ray-system
    values:
      - values/kuberay/ray-cluster/values.yaml.gotmpl
  - chart: prometheus-community/kube-prometheus-stack
    name: kube-prometheus-stack
    namespace: monitoring
    values:
      - values/prometheus-community/kube-prometheus-stack/values.yaml.gotmpl
  - chart: scylla/scylla-operator
    name: scylla-operator
    namespace: scylla
    values:
      - values/scylla/scylla-operator/values.yaml.gotmpl
  - chart: scylla/scylla
    name: scylla
    namespace: scylla
    values:
      - values/scylla/scylla/values.yaml.gotmpl
repositories:
  - name: kuberay
    url: https://ray-project.github.io/kuberay-helm/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: scylla
    url: https://scylla-operator-charts.storage.googleapis.com/stable